export type ChangelogEntry = {
  version: string
  date: string
  summary: string
  details?: string[]
}

export const CHANGELOG: ChangelogEntry[] = [
  {
    version: '0.36.3',
    date: '2026-05-22',
    summary: 'Members page search is server-side now — \"Shurtliff\" (and anyone else past row 1,000 alphabetically) actually shows up.',
    details: [
      "Same PostgREST 1000-row cap that bit the Invitations page in v0.34.2 also hit Members. With 3,297 members in the directory and 2,807 sorting before \"Shurtliff,\" the alphabetical first slice never reached S. Client-side filter couldn't match what was never loaded.",
      "Fix: debounced server-side .or() ilike across first_name / last_name / preferred_name / phone whenever the search box has text — same pattern as the Invitations page. The default (empty search) still loads the first 1,000 alphabetical rows for browsing, and the counter line under the controls now reports honestly: \"Showing first 1,000 of 3,297 — type a name or phone to search the rest\" when truncated, vs. \"N matches for 'shurtliff' (of 3,297 total)\" when filtering. Ward filter applies to both modes.",
    ],
  },
  {
    version: '0.36.2',
    date: '2026-05-22',
    summary: '/join now picks the right row when a member has duplicates — returning members land on their existing data instead of a blank wizard.',
    details: [
      "Bug from Scott testing: tapped /join → his text arrived → tap → blank onboarding wizard, even though he had already completed the survey. Root cause: he had two knit_members rows in his ward with the same name + phone — one manually added before the Tidings sync (onboarded, full data) and one created by the Tidings sync afterward (un-onboarded shell). The lookup picked whichever PostgREST returned first, which happened to be the empty shell.",
      "Fix: when multiple matches exist, prefer the row with onboarding_completed_at set; if neither is onboarded, prefer the older one (more likely the manually-created \"real\" row). Cleaning up the underlying duplicates is a separate follow-up — the Tidings sync should reconcile by ward+phone or ward+name when there's no tidings_member_id on the existing row.",
    ],
  },
  {
    version: '0.36.1',
    date: '2026-05-22',
    summary: 'Self-service member /join page, fixes a bunch of Tidings + Google Sheet sync regressions, and consolidates the sheet/* endpoints.',
    details: [
      "New public page at /join (Landing → \"Get my survey link\"). A member types first name, last name, and phone — backend looks them up in the Tidings-synced ward roster, mints a fresh magic-link, and texts it to them. Doubles as the missionary-shareable invite URL (no need to know each member's contact info upfront) AND as the \"forgot my link\" path for anyone who lost their original SMS. Privacy-by-design: the response is the same generic \"if we found you, we just texted you\" message whether the lookup hit or missed, so the page can't be used to enumerate phones. Phone-level throttle (5 minutes between sends per matched member). Backed by new /api/me/recover endpoint and a new 'self_recovery' notification type.",
      "Google Sheet — Available This Week tab was dumping every synced ward member (3K+ rows of mostly-not-onboarded contacts). Filter now matches the admin Members page's \"Active\" badge: opted in, not paused, onboarding completed, AND at least one availability baseline row.",
      "Google Sheet — missionary writes weren't syncing back to the app because the sheets-pull cron existed in code but was never scheduled in vercel.json. Now wired to run once daily at 23:00 UTC (6pm Central) — Vercel Hobby caps crons at daily granularity, so the WML's \"Sync from sheet now\" button on /admin/sheet remains the on-demand path until we move polling to Supabase pg_cron. \"Members to Invite\", Suggestions request rows, and Log an Outing rows all sync into Knit on the nightly tick or whenever a WML clicks Sync from sheet now.",
      "Tidings opt-outs now propagate into Knit. Previously the apply RPC saw opted_out=true and CONTINUEd, leaving any existing knit_members row's opted_out_at as null forever. The RPC now updates the matching Knit row (idempotent — only sets opted_out_at when it's currently null) before skipping further work.",
      "Consolidated /api/admin/sheet/{create,get,refresh,sync-now} (4 files) into a single /api/admin/sheet endpoint with action routing (GET ?action=get, POST { action: 'create' | 'refresh' | 'sync_now' }) so the new /api/me/recover endpoint fits under Vercel Hobby's 12-function cap. Same pattern as the v0.34.1 google/* collapse. AdminSheet.tsx callers updated. Net function count: 10.",
    ],
  },
  {
    version: '0.36.0',
    date: '2026-05-22',
    summary: 'Gather is consolidated into Glean — Knit\'s /admin/gather is now a redirect, sidebar link points straight at the canonical URL.',
    details: [
      "There are no more three near-identical copies of the Gather page. /admin/gather here is now a redirect to https://glean-blue.vercel.app/admin/gather (the canonical host going forward). Bookmarks still work. The admin sidebar \"Gather ↗\" entry links out directly in a new tab so a click skips the redirect hop.",
      "Why Glean wins: it had the most-evolved version — the suite-app filter that hides Duty / Sparkle Pro / Squarecana users, the Remove-from-suite control, and today's Suggestions section. Steward and Knit's gather copies (including the suggestions block added in v0.35.0 hours ago) are retired.",
    ],
  },
  {
    version: '0.35.2',
    date: '2026-05-22',
    summary: 'Onboarding picker: culture section header reworded as "Languages or cultures you connect with" so the chips read as connection points, not identity labels.',
    details: [
      "Previous label \"Language & culture\" was technically correct but ambiguous — a member who grew up in America might wonder whether to pick European, American, or skip the section entirely. The new header makes the framing explicit: these chips are about connection points the member would love to share (heritage, languages, the cultures the missionaries' friends might be from), not nationality. Skipping is fine; the suggestion engine just uses the rest of the profile.",
      "Decided against adding an 'American' chip — see Scott / Claude exchange in session notes. tl;dr: in a Chicago stake, American is the unmarked default, so adding it would either become noise (almost everyone picks it) or feel othering (some don't). The chips are match signals for the suggestion engine, not identity labels.",
    ],
  },
  {
    version: '0.35.1',
    date: '2026-05-22',
    summary: 'Knit invites two new sport tags, fixes the survey "every Sunday" promise, and starts a 90-day availability refresh cron.',
    details: [
      "Sport tags: Baseball and Ultimate frisbee added to the global library. They appear automatically on the onboarding chip picker — no rebuild needed.",
      "Onboarding confirm screen previously said \"We'll text you every Sunday — just a quick check-in.\" That was a promise we weren't keeping and Scott didn't want anyway. New copy: \"We'll text you again in about 90 days to update your availability. You can always change it sooner by tapping your link.\"",
      "New daily cron at /api/cron/availability-refresh (16:00 UTC = 11am Central) texts each active member whose last refresh was 90+ days ago. \"Active\" = onboarding completed, not paused, not opted out, has a phone. Each send rotates the member's magic-link token, writes a knit_notifications_log row with type='availability_refresh', and is capped at 200/run as a safety belt. New enum value 'availability_refresh' added to knit_notification_type.",
      "Why 90 days vs the original spec's weekly cadence: respect for the member. Weekly texts about availability would have been noise; quarterly fits real-life schedule changes (new jobs, school years, moves). The cron is no-op until members start completing onboarding, so it costs nothing to ship now and have it ready.",
    ],
  },
  {
    version: '0.35.0',
    date: '2026-05-22',
    summary: 'Gather page gained a Suggestions section — review and triage 💡 submissions from any of the five apps.',
    details: [
      "/admin/gather now reads from the shared `app_suggestions` table (where the 💡 button on Magnify / Steward / Glean / Tidings / Knit posts). A per-app summary table shows Open / Backlog / Total counts with a green **New** badge on rows that have unprocessed items.",
      "Below the summary, each open or backlog suggestion lists in full with submitter, date, and source page URL. Three buttons per item: **Add to backlog**, **Mark complete**, **Decline**. Acting on a suggestion removes it from the view — completed and declined are filtered out.",
      "Backed by the new `gather_set_suggestion_status` RPC, locked to super admins via gather_super_admins. RLS read policy added on app_suggestions so super admins can see every suggestion.",
    ],
  },
  {
    version: '0.34.4',
    date: '2026-05-22',
    summary: 'Knit invitations are SMS-only now — Tidings does not carry email addresses, so the email path was dead weight.',
    details: [
      "Removed the \"Send by email\" buttons from the Invitations page and the per-row Invite-link modal on Members. /api/admin/invitations now rejects any channel other than \"sms\". The missionary-sheet \"Members to Invite\" sweep always texts (the Email column on the sheet is ignored for now; we'll drop it from the template the next time we regenerate sheets). Deleted the unused sendInviteEmail helper. RESEND_API_KEY and KNIT_INVITE_FROM env vars can be removed from Vercel — they're no longer read.",
      "Search inputs and the user guide updated to say \"name or phone\" instead of \"name, phone, or email.\" The knit_member_invitations.channel column still allows 'email' so historical rows from v0.32–v0.34.2 still render in the audit history.",
    ],
  },
  {
    version: '0.34.3',
    date: '2026-05-22',
    summary: 'Magic-link 404 fix: invitations were pointing at the wrong vercel.app alias.',
    details: [
      "Members who tapped their SMS invite link got a Vercel 404 NOT_FOUND page. Root cause: the appOriginFromEnv() helper in api/_lib/inviteSend.ts had a hard-coded fallback of https://knit-app.vercel.app — an unclaimed alias — and no NEXT_PUBLIC_APP_URL / VITE_APP_URL was set on the project, so every invite URL pointed nowhere. Fallback is now the actual project alias (https://knit-together.vercel.app) and NEXT_PUBLIC_APP_URL is set on the Vercel project for Production explicitly.",
      "Members invited before this release have invalid links; re-invite them from /admin/invitations and the new link will route correctly.",
    ],
  },
  {
    version: '0.34.2',
    date: '2026-05-22',
    summary: 'Search/filter fixes after the Tidings sync brought in 3,000+ members: Invitations now searches the whole DB, Members has a search bar and ward dropdown.',
    details: [
      "Invitations search was loading the first 2,000 members ordered by first_name and filtering client-side. With 3,297 members in the directory anyone whose name sorted past the cutoff was invisible (\"shurtliff\", \"malli\", \"pope\" missed; \"smith\" hit because at least one Smith was in the first 2K). Switched to debounced server-side .or(...) ilike across first_name / last_name / preferred_name / email / phone — 20 results, runs in the DB, scales independently of the directory size.",
      "Members page now has a search bar (name / phone / email) and a Ward filter dropdown (visible when 2+ wards are in scope). The list also raises the row cap to 5,000 and orders by last_name then first_name, so the alphabetical scan actually matches the alphabetical mental model. A counter under the controls reports how many of the total are showing.",
      "No schema or RLS changes — purely client-side fixes.",
    ],
  },
  {
    version: '0.34.1',
    date: '2026-05-22',
    summary: 'Deploy fix: collapse the three Google OAuth admin endpoints into one so v0.34.0 fits under Vercel Hobby\'s 12-function cap.',
    details: [
      "v0.34.0 added /api/admin/invitations as a 13th serverless function, which hit the Hobby plan's 12-function ceiling — the build compiled but the deploy step failed at \"Deploying outputs.\" /api/admin/google/{authorize,disconnect,status} are now one /api/admin/google endpoint with action routing (GET ?action=status, POST { action: 'authorize' }, POST { action: 'disconnect' }). The OAuth callback stays at /api/admin/google/callback because Google redirects there directly. AdminSheet.tsx callers updated accordingly. Net function count: 11.",
    ],
  },
  {
    version: '0.34.0',
    date: '2026-05-22',
    summary: 'New /admin/invitations page: search a member, click Send, Knit emails or texts them — every send is logged for stake visibility.',
    details: [
      "New `Invitations` nav item between Members and Friends. Type a name (or phone or email) to autocomplete from members in your scope (own ward for WMLs; the whole stake for app super admins), pick the row, then click Send by email or Send by text. Knit emails via Resend (existing v0.32.0 path) or texts via the Tidings edge function (existing v0.33.0 path) — no more handing off to the WML's own Messages/Mail app.",
      "Every send writes a row to the new `knit_member_invitations` table (member, ward, channel, recipient, outcome, who sent it, plus the provider message id when the channel returns one). The same page shows the last 100 sends across the caller's scope so leaders can see who has been invited and whether the send actually succeeded. The missionary-sheet \"Members to Invite\" sweep now logs to this table too, so missionary-initiated invites appear in the same history.",
      "Audience: WMLs see and send for their own ward. Stake president, stake clerk, and the high councilor over missionary work see and send across the entire stake. Permission is enforced server-side via `knit_is_app_super_admin()` / `knit_is_ward_super_admin()`, which read from both `knit_admin_users` and the `gather_user_roles` catalog — so a stake clerk in `gather_user_roles` can invite without needing a `knit_admin_users` row created (though they still need that row to sign in at /admin until the no-admin-row gate is broadened in a follow-up).",
      "The Members tab's per-row \"Invite link\" modal also switches to in-app send: the primary buttons now post to `/api/admin/invitations` and report the outcome inline. The old mailto:/sms: device-handoff is folded into a collapsed \"Or copy the link to send another way\" disclosure.",
      "RLS: `knit_member_invitations` is read-only to authenticated callers via the same helpers; inserts are service-role only (the new endpoint and the sheet-pull sweep). `knit_can_view_ward` is extended to honor the gather_user_roles catalog for stake-level roles so the new page's member search returns rows for stake_clerk and hc_missionary_work without a knit_admin_users seat at the same ward.",
    ],
  },
  {
    version: '0.33.0',
    date: '2026-05-22',
    summary: 'Missionary-designated invites now auto-send via SMS too (cross-project Twilio through Tidings).',
    details: [
      "Closes the email-only gap from v0.32.0. The pullInvites sweep now routes by preference: (1) Email via Resend if there's an email on file — outcome reads \"Emailed 2026-05-22\". (2) Otherwise SMS via the new Tidings `gather-send-invite-sms` edge function — outcome reads \"Texted 2026-05-22\". (3) Email failure with a phone on file automatically falls back to SMS — outcome reads \"Texted 2026-05-22 (email failed)\". (4) If everything fails or no contact info exists, the link is still written to the sheet and the status notes why.",
      "SMS is dispatched cross-project: Knit's Vercel function POSTs to the Tidings edge function with a shared `TIDINGS_INTERNAL_FN_SECRET`. Twilio credentials stay on Tidings; Knit never sees them. Setup auto-applied on Knit's Vercel project (TIDINGS_SMS_URL + TIDINGS_INTERNAL_FN_SECRET set on Production + Development).",
      "Closes #24 — all missionary-designated invite paths (email OR SMS) auto-send without the missionary copying the link manually.",
    ],
  },
  {
    version: '0.32.0',
    date: '2026-05-22',
    summary: 'Missionary-designated invites now auto-send via email (Resend) when a Members to Invite row has an email on file.',
    details: [
      "Upgrade to the v0.31.0 \"Members to Invite\" flow. Previously a missionary ticked a row and Knit wrote the magic link back into the sheet — they then copied it into a personal text/email. Now, when the matched `knit_members` row (or the sheet row itself) has an email, the sync sends a short, friendly invite via Resend automatically. Row status reflects the outcome: \"Emailed 2026-05-22\" on success, \"Link generated 2026-05-22 (no email on file)\" when there's no address, or \"Link generated … (email failed: …)\" with a one-line reason if Resend rejects. The link is always written to the sheet too, so the missionary has a record.",
      "Setup needed for auto-send: set `RESEND_API_KEY` on the Knit Vercel project (env var). Optional `KNIT_INVITE_FROM` to override the From address; defaults to `Knit <noreply@gathered.app>`. Without the API key, the sync silently falls back to v0.31.0 behavior — link written to sheet, no email sent — so the absence of the secret doesn't break anything.",
      "Still a follow-up: SMS auto-send. Needs cross-project plumbing into Tidings' Twilio integration (Twilio creds live on the Tidings project). For now, missionaries with phone-only contacts can still pull the link from the sheet and use the WML's text-invite handoff in /admin/members.",
    ],
  },
  {
    version: '0.31.0',
    date: '2026-05-22',
    summary: 'New "Members to Invite" tab on the missionary sheet — they tick names, Knit generates the magic links.',
    details: [
      "Per the Gathered User Access spreadsheet: \"allow missionaries to designate in their sheet ward members they want to get a Knit availability survey; have Knit send an email or text invitation to that member.\" New `Members to Invite` tab joins the existing 7 sheet tabs. Headers: Full name, Phone, Email, Send invite?, Status, Invite link, Sent at. Header row is hard-locked; Status / Invite link / Sent at are warning-protected (Knit-fill).",
      "Flow: missionary types a ward member's name (and ideally phone or email to disambiguate), checks Send invite? (yes / TRUE / ✓ all accepted). On the next Sync from sheet now (manual or cron), Knit looks up the matching `knit_members` row by ward + name/phone/email, calls `knit_generate_member_magic_link`, and writes the unique URL into Invite link + today's date into Sent at. The missionary then copies the link into a text or email — same magic-link routing as the WML send-invite flow.",
      "If no matching member is found, Status reads \"Not found — add them in /admin/members first\" and the Send flag is cleared so the row doesn't keep retrying. Opted-out members never match.",
      "Server-side auto-send via email or SMS is intentionally NOT in this release. The missionary copy-pastes the generated link — same friction as the v0.29.0 WML mailto:/sms: flow. Auto-send (Resend for email, Twilio cross-project for SMS) is the next-tier upgrade.",
      "Sync result toast now also surfaces \"N invites generated\" alongside the existing suggestions and outings counts.",
    ],
  },
  {
    version: '0.30.0',
    date: '2026-05-22',
    summary: 'Ward members can opt out of Knit (and rejoin) from their availability page.',
    details: [
      'Per the Gathered User Access spreadsheet: "allow a ward member to opt out, which means they no longer want to participate in Knit." The MemberDashboard now has an "Opt out of Knit" link at the bottom of the "Need a break?" section, separated visually from the pause buttons. Clicking it shows a confirm with plain-language explanation ("Missionaries won\'t be paired with you anymore and you\'ll stop getting the weekly check-in. You can rejoin anytime from this same page.").',
      "Once opted out, the dashboard top banner switches to a rose-toned card explaining the state, with a 'Rejoin Knit' button. Member's data (availability, interests, styles) is kept untouched in case they come back — the opt-out is fully reversible from the same magic link.",
      "Backend: new SECURITY DEFINER RPC `knit_member_self_opt_out(member_id, token, opt_out boolean)`. Token-gated like the existing self-service RPCs. Sets `opted_out_at = now()` on opt-out, `NULL` on rejoin. The downstream effects (suggestion engine drops opted-out members, /admin/members shows the rose 'Opted out' badge) were already in place from earlier releases.",
    ],
  },
  {
    version: '0.29.0',
    date: '2026-05-22',
    summary: 'Send availability-survey invites by text or email straight from the Knit app.',
    details: [
      'Per the Gathered User Access spreadsheet, the Ward Mission Leader should be able to "send an email or a text to a ward member from the Knit app that has a link inviting them to fill out their availability survey." The unique-link generation has worked since v0.1 — the gap was that the WML had to copy the link out, switch apps, and compose the message themselves. The invite modal now has three buttons: Text invite, Email invite, and Copy link. Text and Email open your device\'s default app pre-filled with a short, friendly message and the unique link; you just review and hit send. Members with no phone (or no email) get a disabled button with a hint to add it to their profile.',
      'The pre-filled message is intentionally light — first-name only, one-line context ("so we can pair you with missionaries you\'d be a great fit for"), the link, and "takes about a minute." Email gets an extra sentence about the 30-day validity. Easy to tweak in `InviteLinkModal` if a stake wants a different tone.',
      'SMS URL gets a light phone-number cleanup (strips spaces / dashes / parens) since some SMS handlers reject non-digit characters in the path.',
    ],
  },
  {
    version: '0.28.1',
    date: '2026-05-22',
    summary: '"Active" status now requires a completed availability update, not just onboarding.',
    details: [
      'The status badge on /admin/members previously showed "Active" the moment a member finished signup, even if they hadn\'t set any availability. That meant Ward Mission Leaders couldn\'t tell at a glance who was actually ready for a missionary pairing vs. who was still on the hook to fill in their weekly times. Per the Gathered User Access spreadsheet — "Ward members don\'t show as active options until they have completed a Knit availability update" — the badge now requires both: onboarding done AND at least one `knit_availability_baselines` row. A new amber "No availability yet" badge sits in between so leaders can spot who needs a nudge.',
      'DB foundation: new SECURITY DEFINER helpers `knit_member_is_active(member_id)` and `knit_active_member_ids_in_ward(ward_id)`. Same predicate the badge uses; available to any future RLS rewrite, report, or dashboard widget that wants a single source of truth for "active". The suggestion engine in `src/lib/suggestion.ts` already filters per-day/per-slot availability, which is stricter than the predicate — it continues to work unchanged.',
    ],
  },
  {
    version: '0.28.0',
    date: '2026-05-22',
    summary: 'Pull the Tidings member directory into knit_members with one click.',
    details: [
      "/admin/roles now has a \"Sync from Tidings\" button. It calls the new `knit-sync-tidings-members` edge function, which fetches every active contact from Tidings via the shared service-role RPC `gather_tidings_contacts_for_sync`, splits each `full_name` into first + last (last token wins), and upserts into `knit_members` keyed by `tidings_member_id`. Safe to re-run — no duplicates. Surface reports counts: pulled / new / updated / skipped (opted out or blank) / unmapped ward.",
      "Schema: new columns on `knit_members` — `email`, `callings text[]`, `synced_at`, `sync_source`. New `knit_wards.tidings_unit_name` mapping column seeded for all stake wards so \"Hyde Park 1st Ward\" (Tidings) routes to Knit's \"Hyde Park 1st\". GIN index on `knit_members.callings` for fast filtering in the upcoming friend-finder and invite features.",
      "Deferred to follow-ups: weekly pg_cron schedule (same task as Glean's), and the auto-grant-by-calling rule (will land alongside Knit's RLS rewrite when the `knit_*` helpers from v0.27.0 get wired in).",
    ],
  },
  {
    version: '0.27.0',
    date: '2026-05-22',
    summary: 'New /admin/roles screen for assigning the 19 Gathered suite roles + Knit-side helper functions for the Ward Super Admin tier.',
    details: [
      "New Roles tab in the admin sidebar (super-admins only). Lists every signed-in user and lets you tick any of the 19 Gathered roles per person — Stake President through Ward Member. Ward-scoped roles get a ward picker; stake roles cover the stake. Writes to the shared `gather_user_roles` table — the same source of truth Glean's /admin/roles uses and that Tidings syncs into via its trigger.",
      "DB foundation for the eventual Knit RLS work: new SECURITY DEFINER helpers `knit_current_user_has_gather_role(role)`, `knit_is_app_super_admin()` (true for SP / Stake Clerk / HC Missionary Work — the three Knit super-admins per the spreadsheet), and `knit_is_ward_super_admin(ward_id)` (Ward Mission Leader within their ward — the \"ward super admin\" tier). Helpers fall back to the existing `knit_admin_users` table so nothing breaks; they aren't yet wired into Knit's RLS policies.",
    ],
  },
  {
    version: '0.26.3',
    date: '2026-05-22',
    summary: 'Super admins can now create, refresh, and sync missionary sheets.',
    details: [
      'Three sheet endpoints (`/api/admin/sheet/create`, `/refresh`, `/sync-now`) gated on `roleIsWritable(role)`, which only checks `WARD_EDIT_ROLES` (Ward Mission Leader, RS Presidency, EQ Presidency) and ignored the `is_super_admin` flag. As a result, a stake president with `is_super_admin = true` hit "Your role cannot create a sheet" even though the frontend correctly let them try (the frontend uses `canEdit({role, is_super_admin})`).',
      'Added an `adminCanWrite(admin)` helper in `api/_lib/auth.ts` that mirrors the frontend pattern — super admins always pass; otherwise the role must be in `WARD_EDIT_ROLES`. Pointed all three endpoints at the new helper. `roleIsWritable(role)` remains for any role-only checks.',
    ],
  },
  {
    version: '0.26.2',
    date: '2026-05-20',
    summary: 'Suggestion FAB copy trimmed.',
    details: [
      'Removed the "Goes straight to Scott." line from under the prompt in the suggestion modal so it stays focused on the question itself.',
    ],
  },
  {
    version: '0.26.1',
    date: '2026-05-20',
    summary: 'Fixed admin invite failing with "user already registered" when the email already had an auth account.',
    details: [
      'The invite flow used to detect existing auth users via `supabase.auth.admin.listUsers({ perPage: 200 }).find(...)`, which was unreliable — pagination ordering and response shape quirks could miss a user even when only ~30 accounts existed. On a miss it fell through to `inviteUserByEmail`, which then errored because the email was, in fact, already registered (often via the Gathered app switcher).',
      'Replaced the find-by-email step with a deterministic SECURITY DEFINER RPC (`public.knit_find_user_id_by_email`) that queries `auth.users` directly with `lower(email)` and is locked down to the service role. Inviting a high councilor (or anyone) who already has an auth row now attaches the Knit admin role to their existing user_id instead of trying to create a duplicate auth account.',
    ],
  },
  {
    version: '0.26.0',
    date: '2026-05-20',
    summary: 'Suggestion FAB added to the admin area.',
    details: [
      'A small rose lightbulb now floats in the bottom-right corner of every admin screen. Tap it to send a free-form idea or friction note. Submissions land in the shared `app_suggestions` table on the Gathered Supabase project and trigger an email to Scott via Resend, so all of the suite (Knit, Glean, Steward, Tidings, Magnify) feeds one inbox you can triage and mark `in_progress` / `implemented` / `declined`. The submitter\'s name, email, user id, and current page URL are captured automatically when signed in. Member-facing surfaces (the magic-link teaching-friend pages) intentionally do not show the FAB.',
    ],
  },
  {
    version: '0.25.7',
    date: '2026-05-20',
    summary: 'Renamed favicon files to force Chrome cache eviction.',
    details: [
      'The ?v=2 cache-bust from v0.25.6 was not enough — Chrome was still loading the old rings-with-gold-heart icon for Knit specifically (Tidings, which got the same treatment, picked up its new trumpet correctly). Switched to a new filename entirely (favicon.svg → brand-knit.svg, favicon.png → brand-knit.png) so Chrome has no choice but to fetch as a brand-new resource. The original favicon files remain in place so any old bookmarks that fetch /favicon.svg still get the correct new design.',
    ],
  },
  {
    version: '0.25.6',
    date: '2026-05-19',
    summary: 'Cache-busted favicon links so Chrome picks up the new rings-only icon.',
    details: [
      'Chrome maintains a separate favicon cache that ignores normal page refreshes — even after v0.25.5 deployed the correct favicon.svg, users were still seeing the pre-refresh icon (rings-with-gold-heart) in their bookmark bar. Added ?v=2 query strings to the favicon / apple-touch-icon URLs so Chrome treats them as new files and fetches fresh.',
    ],
  },
  {
    version: '0.25.5',
    date: '2026-05-19',
    summary: 'Favicon.svg updated to match new home-screen icon (rose background, white interlocking rings, no heart).',
    details: [
      'The old favicon.svg still rendered the pre-refresh navy / rings-with-gold-heart design, so Chrome\'s bookmark bar and browser tab were showing the wrong glyph (browsers prefer SVG favicons when available). Replaced with a new favicon.svg matching the current PWA icon: rose (#E11D48) background, two white interlocking rings, no heart.',
    ],
  },
  {
    version: '0.25.4',
    date: '2026-05-19',
    summary: 'Knit glyph simplified to just the two interlocking rings — the gold heart at the join is gone.',
    details: [
      'Home-screen / PWA icons (icon-192, icon-512, apple-touch-icon, favicon, public/icon.svg) regenerated without the heart. The two white rings are slightly larger and thicker now that they carry the square on their own.',
      'In-app KnitMark SVG component matched: same rings-only treatment in the header, login, and sidebar.',
    ],
  },
  {
    version: '0.25.3',
    date: '2026-05-19',
    summary: 'In-app KnitMark container color flipped from navy to Knit rose to match the home-screen icon.',
    details: [
      'KnitMark default container fill changed from navy (#1B3A6B) to Knit rose (#E11D48), the same brand color the v0.25.1 home-screen icon and the Gathered "K" chip use. The interior — interlocking white rings + gold heart — is unchanged. The "Knit" wordmark continues alongside the mark wherever it appears.',
    ],
  },
  {
    version: '0.25.2',
    date: '2026-05-19',
    summary: 'Mobile pass — tables collapse intelligently on phones, header action rows stack instead of squishing.',
    details: [
      'Tables on /admin/members, /admin/friends, /admin/outings, and /admin/users no longer force a horizontal scroll on phones. Each table now wraps its less-critical columns in `hidden md:table-cell` / `hidden lg:table-cell` so the most important data — Name, Status, and the actions cell — stays in view at phone width. The remaining columns reappear at the breakpoints where there\'s room. An outer `overflow-x-auto` wrapper plus `min-w-[640px] md:min-w-0` keeps very narrow viewports from clipping content under the sidebar.',
      'Members: Phone visible from sm:, Ward from md:, Language + Availability from lg:.',
      'Friends: Ward from md:, Language + Typical-availability from lg:.',
      'Outings: Member from md:, Notes from lg: (Status badge stays everywhere).',
      'Users: Ward column hidden below md:.',
      'Invite-link modal on /admin/members now drops from p-6 to p-4 sm:p-6 so the URL and Copy button fit on a phone.',
      'Suggest "No matches" card and Sheet status-row headers (Google connection / Sheet bound to this ward) now stack vertically on mobile so the action button isn\'t squeezed up against a long description.',
    ],
  },
  {
    version: '0.25.1',
    date: '2026-05-18',
    summary: 'Home-screen icon redesigned: rose background, white interlocked rings, gold heart at the join.',
    details: [
      'Replaces the dark-on-black "K" home-screen icon with the Gathered "K" chip\'s rose (#E11D48) background plus the two-interlocked-rings-with-gold-heart glyph that already lives inside the app (KnitMark). The heart visually anchors the Mosiah 18:21 reference the app is named for.',
      'icon-192.png, icon-512.png, apple-touch-icon.png, and favicon.png regenerated from a single public/icon.svg master.',
    ],
  },
  {
    version: '0.25.0',
    date: '2026-05-18',
    summary: 'Suite consistency pass (4/5): left sidebar, EN/ES top bar, scripture banner, demo behind settings, new User Guide + Release Notes pages.',
    details: [
      'Admin layout: replaced the horizontal tab strip with a left-side navy sidebar containing a single "Knit" header and primary nav. Matches the Glean shell — same layout target the user called out for Glean, Tidings, and Knit. The duplicate "Knit" header in the old navy top bar is gone.',
      'New persistent top sub-bar carries the scripture banner ("Their hearts [were] knit together in unity and in love." — Mosiah 18:21) and an EN/ES toggle. EN/ES previously had no UI — only i18next browser detection.',
      'Demo removed from the main navigation. The /admin/demo route still works for direct access, but demo mode no longer appears as a top-level tab. Aligns Knit with the suite-wide rule that demo is enabled from Settings.',
      'New /admin/guide route — a structured User Guide page covering what Knit is, the role model, where to start, and language behavior. Linked from the sidebar bottom rail.',
      'New /admin/release-notes route — version-by-version changelog reader pulling from constants/changelog.ts. Linked from the sidebar bottom rail.',
      'PWA manifest theme_color / background_color and the index.html theme-color meta changed from navy (#1B3A6B) to Knit rose (#E11D48) so the home-screen browser chrome and PWA install background match the Gathered "K" chip.',
      'Mobile: the sidebar collapses to a hamburger drawer on small screens. Existing per-page content keeps working unchanged.',
    ],
  },
  {
    version: '0.24.0',
    date: '2026-05-10',
    summary: 'Real Chicago Illinois Stake roster, expanded role model, Settings + Users pages.',
    details: [
      'Seeded the Chicago Illinois Stake and its nine wards (Blue Island, Chicago 2nd, Hyde Park 1st/2nd/3rd, Midway, Moraine Valley, Westchester 1st/2nd) into knit_stakes/knit_wards. Each ward gets an empty Google Sheet binding so WMLs can configure their own.',
      'Expanded the role model from 3 to 5 roles: stake_presidency and high_councilor (both view-only, stake-scoped); ward_mission_leader, relief_society_presidency, and elders_quorum_presidency (all edit, ward-scoped). Old roles stake_president and stake_missionary_hc were renamed in-place via ALTER TYPE; existing rows keep working.',
      'Added is_super_admin flag on knit_admin_users. Super admins bypass scope checks and gain access to user management. Scott (sendscott@gmail.com) is promoted to Stake Presidency + super admin on the Chicago stake.',
      'Rewrote every Knit RLS policy around two new SECURITY DEFINER helpers — knit_can_view_ward(uuid) and knit_can_edit_ward(uuid) — so the rules stay consistent across knit_members, knit_friends, knit_companionships, knit_outings, knit_google_sheet_bindings, knit_interest_tags, knit_wards, knit_stakes, and knit_admin_users.',
      'New page /admin/settings: stake name, ward roster with rename / remove / per-ward sheet-binding status, plus your account card.',
      'New page /admin/users: stake-wide list of Knit admins with role + ward, invite (creates auth user via /api/admin/users/invite), edit role / ward / name in-line, and remove. Super-admin checkbox visible only to other super admins.',
      'Gated every edit affordance — Add member, Add friend, Log outing, Remove buttons, sheet creation/refresh/sync, Google connect/disconnect — behind canEdit(profile). View-only roles see a "View-only" badge instead.',
      'AdminLayout: added Settings and Users tabs (Users only for stake_presidency / super admin), and surfaced a Super-admin chip next to the role label.',
      'Updated demo-mode role switcher to use the new 5-role enum.',
    ],
  },
  {
    version: '0.23.0',
    date: '2026-05-04',
    summary: 'Home-screen icon now shows the rings + heart instead of "K".',
    details: [
      'Added apple-touch-icon.png (180px), icon-192.png, icon-512.png, favicon.png, and a manifest.json so iOS/Android use the actual brand mark when adding Knit to the home screen. Previously only favicon.svg shipped, which iOS does not honor for Add-to-Home-Screen — it would auto-pick a screenshot or fall back to the page-title letter ("K").',
      'Fixed the SPA rewrite in vercel.json so static assets actually serve. The previous regex /((?!api/).*) caught every path that wasn\'t /api/* — including /apple-touch-icon.png and /manifest.json — and routed them to /index.html. iOS would request the icon, get HTML back, and fall back to "K". Updated to /((?!api/|.*\\.).*) so anything with a file extension serves as a file while SPA routes still fall through.',
      'index.html: linked apple-touch-icon, manifest, and apple-mobile-web-app meta tags.',
    ],
  },
  {
    version: '0.22.0',
    date: '2026-05-04',
    summary: 'Brand mark: gold heart at the ring join (matches suite gold accent weight).',
    details: [
      'KnitMark now has a clearly visible gold heart at the intersection of the two interlocking rings, replacing a tiny 2.5px dot that read as just-a-decoration. The heart ties to Mosiah 18:21 — "their hearts were knit together in unity and in love" — the verse the app is named for.',
      'Visual weight now matches the gold accent on Magnify (lens), Steward (check), Glean (wheat), and Tidings (signal sweep), so Knit reads as a real member of the suite instead of a stand-out plain-letter chip.',
      'favicon.svg updated to match.',
    ],
  },
  {
    version: '0.21.1',
    date: '2026-05-04',
    summary: 'Fix Tidings URL in Gathered switcher.',
    details: [
      'tidings.vercel.app → glad-tidings.vercel.app (the previous URL pointed at someone else\'s project).',
    ],
  },
  {
    version: '0.21.0',
    date: '2026-05-04',
    summary: 'Per-app brand stripe — Knit rose now follows from the switcher chip into the chrome.',
    details: [
      '3px knit-primary rose strip between the Gathered jump bar and the navy admin header.',
      'Picks up the same rose used in the Gathered switcher\'s "K" chip — brand identity now extends into the app instead of stopping at the chip.',
    ],
  },
  {
    version: '0.20.4',
    date: '2026-05-04',
    summary: 'Gathered switcher: use canonical short URLs for Magnify and Tidings.',
    details: [
      'magnify-sendscott-dels-projects.vercel.app → magnify-eta.vercel.app',
      'tidings-sendscott-dels-projects.vercel.app → tidings.vercel.app',
    ],
  },
  {
    version: '0.20.3',
    date: '2026-05-04',
    summary: 'Gather admin: Tidings CRUD UI + new gatherTidingsClient wrappers.',
    details: [
      'New src/lib/gatherTidingsClient.ts with fetchTidingsUsers, grantTidingsUser, updateTidingsUser, revokeTidingsUser wrappers.',
      'AdminGather now shows a Tidings users card with full CRUD: add via modal (email, name, role, ward), edit role via inline select, edit ward via inline text (saves on blur), remove with confirm dialog.',
      'List refreshes after every mutation.',
    ],
  },
  {
    version: '0.20.2',
    date: '2026-05-04',
    summary: 'Visual consistency (Wave 6): hero band padding, logo size, min-height, AppSwitcher token.',
    details: [
      'Hero bands on all auth pages (AdminLogin, Signup, ForgotPassword, ResetPassword) standardized to pt-14 pb-24.',
      'Logo size standardized to 44px across all auth headers (was 56px).',
      'form-input and btn-primary utility classes gain min-h-[44px] for 44×44 minimum tap targets.',
      'AppSwitcher chrome color moved to --color-switcher-chrome CSS token (was hardcoded #1e1b4b).',
    ],
  },
  {
    version: '0.20.1',
    date: '2026-05-03',
    summary: 'Gathered switcher: same-tab navigation instead of new tab.',
    details: [
      'Tapping another app in the Gathered dropdown now navigates the current tab instead of opening a new browser tab. Previously each switch left a tab behind.',
    ],
  },
  {
    version: '0.20.0',
    date: '2026-05-03',
    summary: 'Email + password auth alongside the existing magic-link flow.',
    details: [
      '/admin/login now has a tab toggle between Email link (existing) and Password (new). Pick whichever you prefer.',
      '/signup is now a real form — email + password + confirm. After confirming the email link, ask your stake to add you as a Ward Mission Leader or Stake admin.',
      'New /forgot-password and /reset-password pages. The password tab on /admin/login links to /forgot-password.',
      'Cross-app grant via RPC: /admin/gather chip toggles now call gather_grant_app_access / gather_revoke_app_access. Granting Knit creates the knit_admin_users row with a sane role default; the user lands in /admin without a "not yet provisioned" gate.',
    ],
  },
  {
    version: '0.19.0',
    date: '2026-05-03',
    summary: 'Demo role-switcher banner across the admin UI.',
    details: [
      'New role banner sits across the top of every Knit admin screen with a "viewing as <role>" picker (Stake President, Stake HC Missionary, Ward Mission Leader, Member). Independent of the existing /admin/demo Load/Clear seed-data buttons — that controls what the database holds; the banner adds the role-switching narrative on top.',
      'Toggle the banner on/off from /admin/demo (new "Demo role banner" card at the top of the page).',
    ],
  },
  {
    version: '0.18.0',
    date: '2026-05-03',
    summary: 'Get-access page so the auth flow is discoverable.',
    details: [
      'New /signup page explains how to get into Knit for each role: stake leadership get a magic-link sign-in directly, ward mission leaders get invited by the stake high councilor, and members come in through the SMS link the WML sends them. The Sign-in page now links to /signup as a "Get access to Knit" callout.',
      'Knit is magic-link only — there\'s no password to forget — so the typical "Forgot password" flow doesn\'t apply. The /signup page documents that.',
    ],
  },
  {
    version: '0.17.0',
    date: '2026-05-03',
    summary: 'Cross-app user-access management lives inside Knit too.',
    details: [
      'New /admin/gather screen (Stake President / Stake Clerk only) lists every user in the shared "Scott\'s Apps" Supabase project and lets you toggle each of the five Gather apps on or off per user with a chip click. Promotion and demotion of super-admin status (Stake President, Stake Clerk) happens from the same screen. Reachable via a new "Gather" tab in the admin header.',
      'Identical UI lives in Steward and Glean. All three write to the same shared user_apps + gather_super_admins tables, so a grant added in one app instantly lights up the right apps in everyone\'s Gathered switcher.',
    ],
  },
  {
    version: '0.16.0',
    date: '2026-05-03',
    summary: 'Gather suite app switcher — jump between Knit and the other Gather apps from the admin chrome.',
    details: [
      'New AppSwitcher renders a navy "Gathered" strip above the admin header listing the apps you have access to (Magnify, Steward, Glean, Tidings, Knit). Reads from the shared user_apps table, so it stays in sync with whatever the Stake President / Stake Clerk has granted in the cross-app admin screen.',
      'Each app shows as a brand-colored letter chip + one-line blurb so you remember what each one does at a glance.',
      'Knit continues to use Supabase magic-link auth — no password to forget. The cross-app switcher is the only chrome change in this release.',
    ],
  },
  {
    version: '0.15.0',
    date: '2026-05-02',
    summary: 'Sheet protection — missionaries can\'t accidentally break the Knit ↔ Sheet contract anymore.',
    details: [
      'New api/_lib/sheets.ts:applyProtectedRanges + KNIT_PROTECT_TAG: idempotent helper that wipes prior Knit protections and applies a fresh rule set in a single batchUpdate. Existing protections are matched by description prefix, so no duplicates accumulate across reruns.',
      'New api/_lib/sheetSync.ts:protectSpreadsheet wraps a 10-rule canonical set: whole-sheet warnings on Start Here / Available / Friends / Recent (Knit owns these — edits would be wiped by the morning push anyway), hard locks on the header rows of Suggestions / Log an Outing / Urgent Need (with the service account in editors so Knit\'s own writes still go through), and warning-only protections on the Knit-fill columns (Suggestions F:O, Log Outing G, Urgent F).',
      'Hard locks (warningOnly: false) include `editors: { users: [SA email] }` so the service account stays editable; the file owner (the WML who connected Google) can also edit by virtue of being owner.',
      'Wired into provisionSpreadsheet + bindSpreadsheet — every newly-created sheet is protected as soon as initial data is in place.',
      'Wired into /api/admin/sheet/refresh and /api/cron/sheets-morning-push — existing sheet bindings auto-upgrade to the protection set on the next refresh / morning cron, and any drift (a missionary deleting a protection from File menu) self-heals every morning.',
      'New verifyAndRestoreHeaders in api/_lib/sheetPull.ts: before parsing Suggestions or Log Outing rows, it reads row 1 and checks against the canonical header set. If anything drifted (column renamed, deleted, reordered) it rewrites row 1 in place and skips parsing for that pass — preventing the silent "data lands in wrong column" failure mode.',
      'PullReport gains a headersRepaired: string[] field; AdminSheet "Sync from sheet now" surfaces it in the result toast ("Restored headers on: Suggestions, Log an Outing").',
      'Start Here tab body updated with a "note on protections" section explaining what\'s locked and why.',
      'Tradeoff documented: warningOnly: true on the read-only data tabs lets missionaries override if they really need to (e.g., to copy a row out), but the warning is sufficient deterrent and Knit\'s morning push reprojects from the DB regardless. Hard locks are reserved for headers, where any change breaks the parser.',
      'Custom restore mechanism deliberately not built — Google Sheets ships File → Version history with full revision restore for free; the Start Here tab points missionaries there.',
    ],
  },
  {
    version: '0.14.0',
    date: '2026-05-02',
    summary: 'Stake Suite design pass — every admin + member page migrated to suite tokens (slate → gray, dark CTAs → rose .btn-primary, error notices → semantic suite colors).',
    details: [
      'AdminMembers, AdminFriends, AdminOutings, AdminSuggest, AdminSheet, AdminDemo: bulk slate-* → gray-* replacement (text/bg/border/divide/ring/placeholder). Tailwind v4 still ships slate but the suite uses gray.',
      'All dark-slate primary CTAs (rounded-lg bg-slate-900 text-white hover:bg-slate-800) replaced with the .btn-primary class — every primary action is now Knit rose (#E11D48).',
      'Member onboarding step-progress dots and AdminSuggest rank circles changed to bg-knit-primary so the rose accent shows up everywhere it represents progress / position.',
      'Error notice cards: rose-50/rose-200/rose-900 → semantic border-error/30 bg-error/5 text-gray-900. Success notices use border-success/30 bg-success/5. Warnings use border-warning/30 bg-warning/5. All wired to the @theme --color-error / --color-success / --color-warning suite tokens.',
      'Destructive action text (Remove buttons, error messages): text-rose-700 → text-error.',
      'AdminMembers invite-link modal: backdrop is now brand-primary-dark/50 with backdrop-blur — feels native to the suite chrome instead of a generic black-50.',
      'AdminDemo: replaced its inline fuchsia "demo" badge with the suite gold (brand-accent-light + brand-primary-dark text + brand-accent border) — same recipe as the DemoBadge component.',
      'AdminDemo "Clear demo data" button: rose-300 outline → 1.5px error/60 outline with error/5 hover (canonical destructive-secondary look).',
      'MemberDashboard header: added KnitMark next to the wordmark for brand recognition; matches the admin shell.',
      'NotFound: KnitMark + .btn-outline "Go home" — feels like the suite, not a generic 404.',
      'AvailabilityGrid: tap targets now 44×44 sm:48×48, 1.5px gray-200 border, brand-primary-fade selected state with brand-primary check — matches InterestChipPicker / StylePicker.',
      'rounded-xl cards across all admin pages → rounded-md (10px, the suite canonical card radius).',
      'Status Badge palette helpers (slate / emerald / amber / rose) preserved — these are intentional semantic state colors that match the suite\'s soft-pill stage-tint pattern.',
      'No data, schema, or behavior changes — purely visual. Build size: 31.76 kB CSS / 566 kB JS (matches v0.13.0 closely).',
    ],
  },
  {
    version: '0.13.0',
    date: '2026-05-02',
    summary: 'Stake Suite design system applied — Knit now visually matches Magnify, Steward, Tidings, and Glean.',
    details: [
      'New src/tokens.css: canonical Stake Suite Tailwind v4 @theme block — brand-primary navy (#1B3A6B), brand-accent gold (#C9A84C), 10-radius cards, single canonical shadow, suite type scale (11/13/15/17/20/24/30), 9-step neutral grays, semantic + stage colors. Tailwind v4 generates utilities from these (bg-brand-primary, text-knit-primary, rounded-md, shadow-md, font-sans).',
      "Knit's per-app accent: rose (--color-knit-primary #E11D48) — distinct from Magnify (navy), Steward (blue), Tidings (amber), and Glean (gold). Anchors on the Mosiah 18:21 verse the app is named for: \"their hearts were knit together in unity and in love.\"",
      'index.css: import tokens, set body to font-sans + bg-2 / fg-1, plus shared component classes — .form-input (1.5px gray-200 border, 10-radius, knit-primary focus), .btn-primary (knit-primary fill), .btn-outline (1.5px brand-primary border), .btn-ghost, .suite-card, .suite-pill.',
      'New KnitMark component: navy rounded square with two interlocked white rings ("knit together") and a small gold accent dot — same logo treatment as StewardLogo / TidingsLogo / GleanMark.',
      'Replaced the old purple-cyan favicon with a suite-styled navy + white + gold KnitMark SVG.',
      'AdminLayout rewritten: sticky navy (bg-brand-primary) header with KnitMark + wordmark, sticky white tab strip below with rose-accent underline on active tab. Page bg standardized to bg-gray-50.',
      'Landing + AdminLogin redesigned to the suite auth-screen pattern: navy hero up top, white card overlapping below, KnitMark centered, knit-primary CTA.',
      'AdminDashboard: navy/gray suite cards (.suite-card), rose "Open →" link, suite typography scale.',
      'DemoBadge restyled to brand-accent gold (Stake Suite tone) instead of off-palette fuchsia.',
      'InterestChipPicker + StylePicker: 1.5px gray-200 borders, brand-primary-fade selected state with brand-primary text — replaces the dark-slate solid-fill selected look.',
      'index.html: theme-color meta = brand-primary navy, Ionicons CDN module loaded (suite functional-icon library).',
      'No data model changes — all visual / token work. Member onboarding flow still uses the spec-mandated emoji glyphs (🍽 🚗 🪑 🎉 🎓 💬) for non-tech-savvy member tap targets; deferred to a later pass on whether to swap for Ionicons.',
    ],
  },
  {
    version: '0.12.0',
    date: '2026-04-24',
    summary: 'Phase 2 complete — daily push cron + sheet-pull (Suggestions + Log Outing → DB).',
    details: [
      'Slice C: /api/cron/sheets-morning-push + vercel.json cron (12:00 UTC daily). Iterates all bound sheets and re-populates Available / Friends / Recent Outings from live DB.',
      'Slice D: /api/_lib/sheetPull reads the Suggestions and Log an Outing tabs for pending rows (F/G columns empty). Suggestions: parses friend + day + time + need, runs the suggestion algorithm, writes top-5 members + reasons back into columns F-O, logs an audit row in knit_outing_suggestions. Log Outing: parses date + time + friend + member + status + notes, inserts knit_outings row (logged_by = missionary_sheet), writes ✓ in the Synced column.',
      'Name matching: exact "First Last" / preferred_name / nickname / first_name-only. Skips row and logs error on ambiguous or unfound names.',
      'Day/time/status parsing is forgiving: "Sun", "Sunday", "morning", "morn", "happened", "flaked", "cancelled" all accepted.',
      '/api/admin/sheet/sync-now: admin-triggered per-ward sync (same logic as cron, just for one ward). Exposed via a new "Sync from sheet now" button on the bound-state card.',
      '/api/cron/sheets-pull: same sync across all bindings, gated by CRON_SECRET. Not scheduled on Hobby (sub-daily crons require Pro), but endpoint is ready.',
      'New env vars: CRON_SECRET (auto-generated, set via Vercel CLI).',
      'api/_lib/cronAuth.ts: Bearer verification against CRON_SECRET.',
      'api/_lib/suggestion.ts: server-side copy of the scoring logic, decoupled from Database types.',
    ],
  },
  {
    version: '0.11.0',
    date: '2026-04-24',
    summary: 'Sheet integration: one-click Connect Google + Create — replaces the manual bind flow.',
    details: [
      'New Google OAuth user-consent flow: /api/admin/google/authorize + callback + status + disconnect',
      'Migration 2.04: knit_google_oauth table (one row per stake, service-role-only reads, refresh tokens never leave the server)',
      'New /api/admin/sheet/create: creates the sheet in the connected admin\'s Drive, shares with the service account (for ongoing writes) + missionary gmails, lays out the 7 tabs, populates live data, stores binding — all one click',
      'AdminSheet page rewritten: Connect Google Account card, then a simple "Create sheet" form. The manual bind flow is still available via the /api/admin/sheet/bind endpoint as a fallback.',
      'Architectural note: create-time uses OAuth (sheet goes in user\'s Drive, bypasses SA 0-storage issue); refresh-time uses the service account (no OAuth needed after initial share).',
      'Requires new env vars on Vercel: GOOGLE_OAUTH_CLIENT_ID, GOOGLE_OAUTH_CLIENT_SECRET, GOOGLE_OAUTH_REDIRECT_URI — plus a one-time OAuth consent screen config in GCP.',
    ],
  },
  {
    version: '0.10.0',
    date: '2026-04-24',
    summary: 'Sheet integration: switch from auto-create to bind-existing-sheet (works without Google Workspace).',
    details: [
      'Root cause diagnosed: service accounts in consumer-Gmail GCP projects have 0 bytes of Drive storage since early 2024, so spreadsheets.create returns "The caller does not have permission". Affects every personal-account Knit deployment.',
      'New flow: admin creates the sheet themselves at sheets.new, shares it with the service account as Editor, pastes the URL into /admin/sheet. Knit takes over from there.',
      'New endpoint POST /api/admin/sheet/bind: verifies SA can read the sheet, adds our 7 tabs (idempotent), drops default Sheet1, writes Start Here + headers + live data, stores the binding.',
      'New endpoint GET /api/admin/sheet/info: returns the SA email so the UI can display + copy it.',
      'AdminSheet page rewritten: step-by-step instructions with the SA email prominent and copyable.',
      'Richer Google error formatting (HTTP status + reason + SA email) and a /api/admin/sheet/diagnose endpoint that probed each API call until we found the storage-quota root cause.',
    ],
  },
  {
    version: '0.9.0',
    date: '2026-04-24',
    summary: 'Demo data mode — one-click seed/clear of a realistic ward so you can test without hand-entering everything.',
    details: [
      'Migration 2.02: is_demo boolean on knit_members / knit_friends / knit_outings (plus partial indexes)',
      'Migration 2.03: knit_load_demo_data(ward), knit_clear_demo_data(ward), knit_demo_status(ward) — SECURITY DEFINER with explicit admin scope check',
      'Seed inserts 6 members (2 Spanish speakers, 1 not-yet-onboarded for variety), 3 friends (investigating / progressing / on date), 8 outings across the last 45 days (mostly happened, one flaked, one scheduled)',
      'Load is idempotent: if demo rows exist it returns current counts instead of duplicating',
      'Clear deletes outings → friends → members in order, cascades cleanly',
      '/admin/demo page: status card with counts, Load + Clear buttons, explanation of what is in the dataset',
      'Demo badge pill shown on every demo row in Members / Friends / Outings lists',
    ],
  },
  {
    version: '0.8.0',
    date: '2026-04-24',
    summary: 'Phase 2 Slice A — provision per-ward Google Sheet. Missionaries now have their own workspace.',
    details: [
      'First-ever /api/ serverless functions for this project: provision / refresh / get sheet binding',
      'Google Sheets + Drive via service account (no OAuth consent flow — pure service-to-service)',
      "Creates a spreadsheet, writes 7 tabs (Start Here, Available This Week, Friends We are Teaching, Suggestions, Log an Outing, Urgent Need, Recent Outings), shares with the missionaries' Gmail addresses as Editors",
      'Initial population: Available + Friends + Recent Outings rendered from live DB state',
      '/admin/sheet page with provision form + bound-state view + "Refresh data tabs now" button',
      'Migration 2.01: knit_google_sheet_bindings.shared_emails text[] column',
      'Still to come in Phase 2: cron-based morning push + daytime pull of Suggestions and Log Outing rows',
      'REQUIRES user setup of GOOGLE_SERVICE_ACCOUNT_EMAIL + GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY + SUPABASE_SERVICE_ROLE_KEY + SUPABASE_URL in Vercel',
    ],
  },
  {
    version: '0.7.0',
    date: '2026-04-23',
    summary: 'Slice G — friend interests picker + /admin/outings log.',
    details: [
      'Add Friend form now has the InterestChipPicker so interest_tag_ids is populated — suggestion algorithm can now score interest overlap',
      '/admin/outings: list of recent outings + inline Log outing form (friend, member, date, slot, status, outcome notes)',
      'Outings feed the suggestion algorithm: freshness (days since last happened), reliability (baseline 3 + happened cap +3), prior-pairing bonus, recent-pairing penalty',
      'scheduled_at composed from date + slot hour (9am / 2pm / 7pm local); scheduled_time_slot stored for display',
      'Status badge with 6 tones (scheduled, happened, flaked, rescheduled, canceled, needs_checkin)',
      'Dashboard card for Outings now links; nav gets an Outings tab',
    ],
  },
  {
    version: '0.6.0',
    date: '2026-04-23',
    summary: 'Slice F — suggestion algorithm and /admin/suggest UI. Pick a friend + day + slot → top 5 ranked members with reasons.',
    details: [
      'Spec §7 scoring implemented in TypeScript (src/lib/suggestion.ts): language, style-match, interest overlap (cap 5), freshness (min(days/14, 5)), reliability (3 baseline + 1 per happened cap +3), prior-success bonus, recent-pairing penalty',
      'Hard filters: paused, opted-out, baseline availability, language compatibility, participation-style match (if need provided)',
      '/admin/suggest page: friend + day + time-slot + optional need → ranked list with per-candidate reasons and score',
      'Empty-state hints: distinct copy for "no one available" vs "fewer than 3" vs all-filtered (expandable list of why each was filtered)',
      'AdminLayout gets a Suggest tab; dashboard card now links',
      'Excludes friends whose teaching_status is baptized or lost_contact from the dropdown',
    ],
  },
  {
    version: '0.5.0',
    date: '2026-04-23',
    summary: 'Slice E — 6-screen member onboarding + inline edits on /me for availability, interests, and participation styles.',
    details: [
      'Migration 1.12: RPCs knit_member_self_save_availability / save_interests / save_styles / complete_onboarding — all bulk-replace semantics, token-validated',
      'Opened anon SELECT on global knit_interest_tags (ward_id null) and knit_participation_styles so the wizard renders without a Supabase session',
      'MemberOnboarding — 6 screens: welcome → what-we-ask → days → interests → styles → confirm. Saves at each Next so progress survives a refresh.',
      '/me branches: not-yet-onboarded members see the wizard; otherwise the dashboard',
      'Dashboard sections now have inline Edit → picker → Save/Cancel for each of availability, interests, styles',
      'Reusable InterestChipPicker (grouped by category) and StylePicker (icon-labelled multi-select buttons)',
    ],
  },
  {
    version: '0.4.0',
    date: '2026-04-23',
    summary: 'Slice D — member magic link end-to-end. Admin can issue a link; member visits it, sees their dashboard, and can pause.',
    details: [
      'Migration 1.11: Postgres RPCs knit_generate_member_magic_link, knit_member_self_read, knit_member_self_pause — token stored as sha256, all crypto server-side, no service role or serverless functions needed',
      'Admin Members tab: "Invite link" / "New link" button on each row → copy-to-clipboard modal with the personal URL',
      '/m/:memberId/:token verifies via RPC, stores {memberId, token} in localStorage, redirects to /me',
      '/me shows name, ward, availability (read-only for now), interest chips, participation styles, and pause buttons (30 / 90 days, unpause)',
      'Sign out clears localStorage and returns to landing',
      'Editing availability + interests + styles from /me and the 6-screen onboarding flow come in the next slice',
    ],
  },
  {
    version: '0.3.1',
    date: '2026-04-23',
    summary: 'Slice C — full names for members + structured day × time-slot availability grid for both members and friends.',
    details: [
      'Migration 1.10: knit_members.first_name + last_name columns',
      'Reusable AvailabilityGrid component (7 days × morning/afternoon/evening cells, 48px touch targets)',
      'Members form: first + last name, phone, language, ward, availability → writes knit_availability_baselines rows',
      'Friends form: availability picker replaces free-text typical_availability field; serializes to readable string like "Tue, Thu evenings; Sat mornings"',
      'Members list now shows an "Available" column with the same readable format',
      'slotsToString() groups days sharing identical slots for compact display',
    ],
  },
  {
    version: '0.3.0',
    date: '2026-04-22',
    summary: 'Phase 1 Slice B — Members + Friends tabs with add/list/remove. Admins can seed a real ward.',
    details: [
      'Added knit_members.phone column for pre-Tidings manual entries (nullable + indexed partial)',
      'Regenerated TypeScript types',
      '/admin/members: list + inline add form (display name, phone, language, ward)',
      '/admin/friends: list + inline add form (name, nickname, phone, language, teaching status, typical availability)',
      'AdminLayout sub-nav with Dashboard / Members / Friends tabs',
      'Dashboard cards for Members and Friends now link to their tabs',
      'Stake-level admins see a ward picker; WML has ward auto-selected',
      'Shared .form-input Tailwind component for consistent form styling',
    ],
  },
  {
    version: '0.2.1',
    date: '2026-04-22',
    summary: 'Phase 1 Slice A — admin auth + router shell. Sign in via Supabase magic link, role-aware dashboard.',
    details: [
      'React Router with routes: / (Landing), /admin/login, /admin/callback, /admin (protected), /m/:id/:token, /me',
      'AuthProvider wraps the app; useAuth + useAdmin hooks',
      'AdminLayout checks knit_admin_users; shows "not yet provisioned" screen for signed-in users without an admin row',
      'Admin dashboard shows role + scope + placeholder tabs for the Phase 1 milestones still to come',
      'vercel.json adds SPA rewrites so deep links (e.g. /admin/login) work on refresh',
    ],
  },
  {
    version: '0.2.0',
    date: '2026-04-22',
    summary: 'Phase 1 database foundation — all 16 knit_ tables, RLS, seeds, TypeScript types.',
    details: [
      'Migration 1.1: knit_stakes, knit_wards, knit_admin_users + knit_current_admin() SECURITY DEFINER helper',
      'Migration 1.2: knit_members, knit_interest_tags, knit_participation_styles + member join tables',
      'Migration 1.3: knit_availability_baselines, knit_availability_exceptions',
      'Migration 1.4: knit_friends, knit_companionships, knit_outings, knit_outing_suggestions',
      'Migration 1.5: knit_notifications_log, knit_google_sheet_bindings',
      'Migration 1.6: seeded 7 participation styles + 47 global interest tags',
      'Migration 1.7: generated TypeScript types into src/lib/database.types.ts, Supabase client now typed',
      'Migration 1.8: advisor fixes — function search_path locked, auth.uid() wrapped for initplan caching, covering indexes added, FOR ALL policies split into INSERT/UPDATE/DELETE on knit_wards + knit_interest_tags to remove overlap with FOR SELECT',
      'All knit_ tables are RLS-enabled; admin scope enforced via knit_current_admin() helper',
    ],
  },
  {
    version: '0.1.3',
    date: '2026-04-22',
    summary: 'Fix: runtime dependencies were missing from package.json, breaking Vercel build.',
    details: [
      'First Vercel build failed with TS2307 "Cannot find module" for react-i18next, supabase-js, clsx, etc.',
      'Root cause: initial background npm install saved to node_modules but not package.json',
      'Reinstalled with explicit --save, all runtime deps now declared',
      'Build verified locally (250kb JS / 8kb CSS)',
    ],
  },
  {
    version: '0.1.2',
    date: '2026-04-22',
    summary: 'Phase 0 wrap-up: googleapis installed (Phase 2 prep), shadcn/ui components.json configured, initial push to GitHub.',
    details: [
      'googleapis npm package added for Phase 2 Sheets integration (server-side only)',
      'components.json configured for shadcn/ui CLI — slate base, @/components, @/lib/utils aliases',
      'Repo pushed to sendscott-del/knit-app on GitHub',
    ],
  },
  {
    version: '0.1.1',
    date: '2026-04-22',
    summary: 'Phase 0 architectural decision: consolidate Knit into shared Scott\'s Apps Supabase project with knit_ table prefix.',
    details: [
      'Free-tier org caps at 2 projects; Tidings occupies the second slot',
      'Every Knit table will be prefixed knit_ (knit_members, knit_wards, knit_outings, etc.)',
      'Matches existing chores_ / duty_ / steward_ / sq_ / bloom_ pattern in Scott\'s Apps',
      'Tidings remains a separate project (jdlykebsqafcngpntxma) for cross-project reads',
      'Spec (CLAUDE.md) and project memory updated with the decision and rationale',
    ],
  },
  {
    version: '0.1.0',
    date: '2026-04-22',
    summary: 'Phase 0 scaffold — Vite + React + TS, Tailwind v4, i18next (en/es), Supabase client stub.',
    details: [
      'Project scaffolded with Vite 8 + React 19 + TypeScript',
      'Tailwind v4 configured via @tailwindcss/vite plugin',
      'i18next wired with en/es namespaces (common, onboarding, admin, sheet) — es values stubbed as TODO',
      'Supabase client module + .env.example created',
      'Path alias @/* mapped to src/*',
    ],
  },
]

export const CURRENT_VERSION = CHANGELOG[0].version

export const APP_NAME = 'Knit'

